### ISSUE TITLE
publication checklist / reminders

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#296]
* [x] polish [new courses parent page](https://github.com/w3c/wai-fundamentals-overview/blob/when-course-list-publish/content/courses.md) and update the navigation.yml
* [x] update https://www.w3.org/WAI/courses/ with link to course list

**Comment by leticiaseixas** [comment]
- [ ] merge PR #331 with submissions updates on registration type
